### ISSUE TITLE
Remove listener

### ISSUE THREAD

**Issue by adrianoleiterodrigues** [jkbz64/capacitor-datawedge#8]
Hello!
First I would like to thank you for the plugin, it helped me a lot!
Second, I would like to know how I can remove an listener. I use the listener on two separate pages and on exit I want to remove the event to avoid conflicts.
I tried in two ways:

First:
```
this.dataWedgeListener = DataWedge.addListener("scan", async (event) => {
  console.log(event.data);
});

this.dataWedgeListener.remove();
```
Second:
```
DataWedge.addListener("scan", async (event) => {
  console.log(event.data);
});

DataWedge.removeAllListeners();
```

Can you help me?

Thanks!

**Comment by jkbz64** [comment]
I don't think there is any other way than the ways you tried to remove the listener. The plugin does not implement these methods, it all gets inherited from the capacitor plugin class so that's definitely weird these don't work for you, did you try to await the results and check what do they return? They should return true, if that happens the listener should be closed as it's handled by capacitor itself.

**Comment by adrianoleiterodrigues** [comment]
I checked further and saw that it really was working, the error I had was associated with a DataWedge configuration on the device.
When reading a barcode, the input was being filled with a duplicate code, which caused the error.
So I thought it might be the event being received more than once.

Thanks a lot!
